name: Docker Image CI

on: 
  repository_dispatch:
    types:
      - end-to-end

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Triggered by the dispatcher
      run: |
        echo "repository_dispatch triggered"
